# action.yml
name: 'Docker Run Action'
description: 'Run a docker image with given options and arguments'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  registry:
    description: 'Registry'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: true
  args:
    description: 'Arguments to pass to the image entrypoint'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
