name: lint

on:
  push:
    branches: [main]  # Or the name of your default branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.run-increment-version.outputs.new-version }}
    steps:
      - name: Run the increment-version action
        id: run-increment-version
        uses: GenapsysInc/internal-actions/reusable-actions/increment-version@main
        with:
          token: ${{ secrets.GH_REST_API_TOKEN }}
          json: <path/to/repo-data.json>
          use-date: <true|false>, append date string to generated version tag
          protect-tag: <true|false>, protect the generated tag in GitHub
