name: mypy

on:
  push:
    branches: [main]  # Or the name of your default branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Run mypy
        uses: GenapsysInc/internal-actions/reusable-actions/mypy@main
        with:
          python-version: <default 3.10>
          requirements-txt: <path/to/requirements.txt>
          build-command: <optional command to run before mypy>
          mypy-version: <default latest>
          args: <default --exclude docs --exclude confluence .>
