name: Build Docs
description: Build documentation based on sphinx

inputs:
  token:
    description: "Token to pull the docbuilder container"
    required: true
  confluence_secret:
    description: "Confluence API token for publication"
    required: false
    default: ''
  api_dirs:
    description: "Directories to build api docs for (space separated) - str"
    required: false
    default: ''
  build_confluence:
    description: "Build documentation as pages for Confluence - boolean"
    required: false
    default: false
  publish_confluence:
    description: "Publish Confluence pages - boolean"
    required: false
    default: false
  build_html:
    description: "Build documentation as HTML - boolean"
    required: false
    default: false
  publish_html:
    description: "Publish HTML to github pages - boolean"
    required: false
    default: false
  version:
    description: "The version string to use for HTML rendering - string"
    required: false
    default: ''
  warn_as_errors:
    description: "Treat warnings raised as errors - boolean"
    required: false
    default: false
  build_options:
    description: "User specified options for sphinx build - string"
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
    - name: Run docbuilder
      uses: GenapsysInc/internal-actions/reusable-actions/docker-run@main
      with:
          username: ${{ github.repository_owner }}
          password: ${{ inputs.token }}
          registry: ghcr.io
          image: ghcr.io/genapsysinc/docbuilder:latest
          options: -v ${{ github.workspace }}:/repo
          args: ${{ (inputs.confluence_secret && '-s') || '' }} ${{ inputs.confluence_secret }}
                ${{ (inputs.api_dirs && '-d') || '' }} ${{ inputs.api_dirs }}
                ${{ (fromJSON(inputs.build_confluence) && '-c') || '' }} 
                ${{ (fromJSON(inputs.publish_confluence) && '-p') || '' }} 
                ${{ (fromJSON(inputs.warn_as_errors) && '-w') || '' }}
                ${{ (fromJSON(inputs.build_html) && '-m') || '' }}
                ${{ (inputs.version && '-v') || '' }} ${{ inputs.version }}
                ${{ (inputs.build_options && '-u " ') || '' }}  ${{ inputs.build_options }} ${{ (inputs.build_options && ' "') || '' }}
    - name: Build GitHub Pages
      if: ${{ fromJSON(inputs.publish_html) && fromJSON(inputs.build_html)}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: _builder/html
