name: build-docs
description: Build documentation based on sphinx

inputs:
  token:
    description: "Token to pull the docbuilder container"
    required: true
  confluence_secret:
    description: "Confluence API token for publication"
    required: false
    default: "XXXXXXXX"
  build_confluence:
    description: "Build documentation as pages for Confluence - boolean"
    required: false
    default: null
  publish_confluence:
    description: "Publish Confluence pages - boolean"
    required: false
    default: null
  build_html:
    description: "Build documentation as HTML - boolean"
    required: false
    default: null
  warn_as_errors:
    description: "Treat warnings raised as errors - boolean"
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: genapsysinc/internal-actions
        path: internal-actions
        ref: main
        token: ${{ inputs.token }}
    - name: Run docbuilder
      uses: GenapsysInc/internal-actions/reusable-actions/docker-run-action@main
      with:
          username: ${{ github.repository_owner }}
          password: ${{ inputs.token }}
          registry: ghcr.io
          image: ghcr.io/genapsysinc/docbuiler:latest
          options: -v ${{ github.workspace }}:/repo
          args: -s ${{inputs.confluence_secret}} ${{ inputs.build_confluence == true && '-c' || '' }} ${{ inputs.publish_confluence == true && '-p' || '' }} ${{ inputs.warn_as_errors == true && '-w' || '' }}