name: submodule-check-action
description: Asserts submodules in the calling repository are on commits in the commit history of their default branch

inputs:
  token:
    description: "Github token for authentication to REST API"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
    - name: Checkout internal-actions
      uses: actions/checkout@v3
      with:
        repository: genapsysinc/internal-actions
        path: internal-actions
        ref: main
        token: ${{ inputs.token }}
    - name: Set up Python 3.10 and install dependencies
      uses: genapsysinc/internal-actions/reusable-actions/setup-python@main
      with:
        requirements-txt: 'internal-actions/action_utils/requirements.txt'
    - name: Run check_submodule_commits.py with input args
      shell: bash
      run: |
        export PYTHONPATH="`pwd`/internal-actions"
        python internal-actions/action_utils/check_submodule_commits.py \
          -s ${{ inputs.token }} \
          -r .
