name: fork-check
description: Assert base and head refs in a PR are in the GenapsysInc fork of the repository

inputs:
  fail-check:
    description: Fail the calling workflow's status check
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Base ref pass, head ref fail
      if: ${{ !contains(github.event.pull_request.head.label, 'GenapsysInc') }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Pull Request head branch `${{ github.event.pull_request.head.label }}` is not owned by Organization user\n\n\
              Use of private forks has been deprecated and will be strictly enforced starting **July 1st, 2022**'
          })
