name: increment-version
description: Create + push new tag based on calling repo's current version and version information in a metadata JSON file

inputs:
  json:
    description: Path to metadata JSON file containing version
    required: true
    default: repo-data.json
  use-date:
    description: Include a date string in the tag
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
    - name: Checkout internal-actions
      uses: actions/checkout@v3
      with:
        repository: genapsysinc/internal-actions
        path: internal-actions
        ref: tag-commit-action
        token: ${{ inputs.token }}
    - name: Run tag_commit.py with given arguments - lays down a new tag or errors if specified version is invalid
      shell: bash
      run: |
        export PYTHONPATH="`pwd`/internal-actions"
        python internal-actions/action_utils/tag_commit.py \
          -r . \
          -j ${{ inputs.json }} \
          ${{ (fromJson(inputs.use-date) && '-d') || '' }}
    - name: Push new tag to GitHub - only runs when the calling workflow was triggered by a push event
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: git push --tags
