name: SonarQube
description: Runs SonarQube on the repository using this action

inputs:
  token:
    description: SonarQube Token
    required: true
  url:
    description: SonarQube Host URL
    required: true
  coverage-xml:
    description: XML coverage report file content
    required: true
    default: ""

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Write coverage
      shell: bash
      run: |
        mkdir coverage-reports/
        echo ${{ inputs.coverage-xml }} > coverage-reports/coverage-report.xml
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.token }}
        SONAR_HOST_URL: ${{ inputs.url }}
