name: SonarQube
description: Runs SonarQube on the repository using this action

inputs:
  token:
    description: SonarQube Token
    required: true
  url:
    description: SonarQube Host URL
    required: true
  fail_when_red:
    description: Should the build fail when the SonarQube Quality Gate is red?
    default: true
    required: true


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.token }}
        SONAR_HOST_URL: ${{ inputs.url }}
    - uses: sonarsource/sonarqube-quality-gate-action@master
      if: ${{ inputs.fail_when_red == true }}
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ inputs.token }}
