name: SonarQube

on:
  push:
    branches: [main]  # Replace with branches you want to run on
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: GenapsysInc/internal-actions/reusable-actions/sonarqube@main
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          url: ${{ secrets.SONAR_HOST_URL }}
