name: team-approval-check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  call-workflow:
    uses: GenapsysInc/internal-actions/.github/workflows/team-approval-action.yml@main
    with:
      # Teams with spaces should have spaces replaced with either a '-' or '_', casing does not matter
      # i.e. "Developer Experience" could be listed as "developer-experience"
      # This will allow proper input handling with the reuseable team-approval-action workflow
      # See https://github.com/orgs/GenapsysInc/teams for the available teams for the check
      teams: <team 1> <team 2> ... <team n>
    secrets:
      token: ${{ secrets.GH_REST_API_TOKEN }}
