name: team-approval-check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  call-workflow:
    uses: GenapsysInc/internal-actions/.github/workflows/team-approval-action.yml@main
    with:
      repo: ${{ github.event.repository.name }}
      pull: ${{ github.event.pull_request.number }}
      # Teams with spaces i.e. "developer experience" should have spaces replaced with either a '-' or '_'
      # This will allow proper input handling with the reuseable team-approval-action workflow
      teams: <team1> <team2> <team3>
    secrets:
      token: ${{ secrets.GH_REST_API_TOKEN }}
