name: check-version
description: Assert repo version was bumped if a git diff implies it should have been

inputs:
  json:
    description: Path to metadata JSON file containing version
    default: repo-data.json
  include-paths:
    description: Directories, file paths, or wildcards that when changed should incur a version bump
    default: null
  exclude-paths:
    description: Directories, file paths, or wildcards that should be excluded from the diff check, taking priority over include-paths
    default: null
  token:
    description: Token to checkout internal-actions
    required: true

runs:
  using: composite
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull tags down
      shell: bash
      run: git fetch origin --tags
    - name: Checkout internal-actions
      uses: actions/checkout@v3
      with:
        repository: genapsysinc/internal-actions
        path: internal-actions
        ref: version-bump-check-test
        token: ${{ inputs.token }}
    - name: Set up Python 3.10 and install dependencies
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        requirements-txt: 'internal-actions/action_utils/requirements.txt'
    - name: Run check_version.py with given arguments
      shell: bash
      run: |
        export PYTHONPATH="`pwd`/internal-actions"
        python internal-actions/action_utils/check_version.py \
          -j ${{ inputs.json }} \
          -s ${{ inputs.token }} \
          -p ${{ github.event.number }} \
          -r ${{ github.event.repository }} \
          -o ${{ github.event.organization }} \
          -i ${{ inputs.include-paths }} \
          -e ${{ inputs.exclude-paths }}
