name: check-version
description: Check that the repo data JSON was updated if functional changes were made

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Run the check-version action
        id: run-check-version
        uses: GenapsysInc/internal-actions/reusable-actions/check-version@main
        with:
          json: path/to/repo-data.json  # Remove if repo-data.json lives in root directory of the repo
          include-paths: '*.py static'
          exclude-paths: 'docs action_utils/tests static/*.txt'
