name: pytest Action
description: Setup Python, install dependencies in given requirements.txt files, and run pytest via coverage run

inputs:
  python-version:
    description: Version of python to setup
    default: '3.10'
    required: true
  requirements-txt:
    description: Relative path to requirements.txt file. Wildcards can be submitted as well
    default: null
    required: true
  build-command:
    description: Build command to be executed prior to running unit tests.
    default: null
    required: false
  coverage-args:
    description: Additional arguments passed to coverage run, before invoking pytest
    default: null
    required: false
  pytest-args:
    description: Additional arguments passed to pytest.
    default: -v
    required: false
  token:
    description: Token to checkout internal-actions
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python version ${{ inputs.python-version }}
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        requirements-txt: ${{ inputs.requirements-txt }}
        build-command: ${{ inputs.build-command }}
    - name: Install pytest, coverage, and other dependencies for testing
      run: pip install pytest pytest-cov pytest-xdist psutil
      shell: bash
    - name: Checkout internal-actions
      uses: actions/checkout@v3
      with:
        repository: genapsysinc/internal-actions
        path: internal-actions
        ref: pytest-xdist
        token: ${{ inputs.token }}
    - name: Patch pluggy._manager
      run: python internal-actions/action_utils/patch_pluggy_manager.py
      shell: bash
    - name: Run pytest and capture code coverage
      run: pytest -p pytest_cov --cov --junitxml=pytest-test-report.xml ${{ inputs.pytest-args }}
      shell: bash
    - name: Archive test and coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: 'pytest-*-report.xml'
