name: 'pytest Action'
description: 'Setup Python, install dependencies in given requirements.txt files, and run pytest'

inputs:
  python-version:
    description: 'Version of python to setup'
    default: '3.10'
    required: false
  requirements-txt:
    description: 'Relative path to requirements.txt file. Wildcards can be submitted as well'
    default: null
    required: false

outputs:
  coverage-xml:
    description: 'coverage-report.xml file content'
    value: ${{ steps.set-coverage-output.outputs.coverage-xml }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python version ${{ inputs.python-version }}
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        requirements-txt: ${{ inputs.requirements-txt }}
    - name: Install pytest and pytest-cov
      run: pip install pytest pytest-cov
      shell: bash
    - name: Run pytest and capture code coverage
      run: 'python -m pytest -v --cov --cov-report xml:coverage-report.xml'
      shell: bash
    - name: Set coverage output
      id: set-coverage-output
      run: echo "::set-output name=coverage-xml::$(cat coverage-report.xml)"
      shell: bash
    - name: test?
      run: echo ${{ steps.set-coverage-output.outputs.coverage-xml }}
