name: pytest Action
description: Setup Python, install dependencies in given requirements.txt files, and run pytest

inputs:
  python-version:
    description: Version of python to setup
    default: '3.10'
    required: true
  requirements-txt:
    description: Relative path to requirements.txt file. Wildcards can be submitted as well
    default: null
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python version ${{ inputs.python-version }}
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        requirements-txt: ${{ inputs.requirements-txt }}
    - name: Install pytest and pytest-cov
      run: pip install pytest pytest-cov
      shell: bash
    - name: Run pytest and capture code coverage
      run: 'python -B -m pytest -v --junitxml=pytest-test-report.xml --cov --cov-report xml:pytest-coverage-report.xml'
      shell: bash
    - name: Archive test and coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: 'pytest-*-report.xml'
