on:
  pull_request:
    types: [opened, synchronize, reopened]

# Just run the documentation but don't publish it.  This is good to check that the documents build without errors

jobs:
  call-workflow:
    name: Run the documentation builder workflow
    runs-on: ubuntu-latest
    steps:
      - name: Documentation build
        uses: GenapsysInc/internal-actions/reusable-actions/build-docs@meta-docs
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          confluence_secret: ${{ secrets.CONFLUENCE_SECRET }}
          build_confluence: true
          publish_confluence: false
          build_html: true
          publish_html: false
          warn_as_errors: false
          api_docs: "action_utils"

