name: example-called-workflow-1

on:
  workflow_call

jobs:
  # job-1:
  #   name: Job 1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print out current job name
  #       run: echo ${{ job.name }}
  # job-2:
  #   name: Job 2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print out current directory
  #       run: echo `pwd`
  job-3:
    name: Job 3
    runs-on: ubuntu-latest
    steps:
      - name: Write a file
        run: echo "hello-world" > to-archive.txt
      - name: Archive the file!
        uses: actions/upload-artifact@v3
        with:
          name: my-archived-file
          path: to-archive.txt
  job-4:
    name: Job 4
    needs: job-3
    runs-on: ubuntu-latest
    steps:
      - name: Pull down the archive!
        uses: actions/download-artifact@v3
        with:
          name: my-archived-file
          path: downloaded-archive
      - name: Print file contents
        run: cat downloaded-archive/to-archive.txt
