name: example-calling-workflow

on:
  push:
    branches: [actions-demo]


jobs:
  run-workflow-1:
    name: Run the first reusable workflow
    uses: GenapsysInc/internal-actions/.github/workflows/called-workflow-1.yml@actions-demo
  run-workflow-2:
    name: Run the second reusable workflow
    uses: GenapsysInc/internal-actions/.github/workflows/called-workflow-2.yml@actions-demo
    with:
      input-string: Burritos rock
      print-string: true
