name: hello world
on:
  push:
    branches: [docker-build-upload]

jobs:
  run-hello-world-docker:
    runs-on: ubuntu-latest
    steps:
      - name: run ubuntu:latest
        uses: GenapsysInc/internal-actions/reusable-actions/docker-run@docker-build-upload
        with:
          image: alpine:latest
          options: -e ENV_VAR="env_var" --entrypoint bash
          args: -c echo $ENV_VAR
