name: Org Policies Reusable Workflow

on:
  workflow_call

jobs:
  fork-check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run the fork-check action
        uses: GenapsysInc/internal-actions/reusable-actions/fork-check@fork-check
        with:
          close-pull: false
