name: Org Policies

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '35 17 * * 0'

jobs:
  run-jobs:
    name: Run Jobs
    uses: GenapsysInc/internal-actions/.github/workflows/org-policies.yml@main
