name: Org Policies

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 16 * * *'

jobs:
  run-jobs:
    uses: GenapsysInc/internal-actions/.github/workflows/org-policies.yml@fork-check
