name: SonarQube

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.10' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run pytest, Python version ${{ matrix.python-version }}
        uses: GenapsysInc/internal-actions/reusable-actions/pytest@main
        with:
          python-version: ${{ matrix.python-version }}
          requirements-txt: action_utils/tests/requirements.txt
  run-sonarqube:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: GenapsysInc/internal-actions/reusable-actions/sonarqube@main
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          url: ${{ secrets.SONAR_HOST_URL }}
