name: Static Analysis Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        default: '3.10'
        type: string
      requirements-txt:
        type: string
      build-command:
        type: string
      run-pylint:
        default: true
        type: boolean
      pylint-version:
        type: string
      pylint-args:
        type: string
      run-mypy:
        default: true
        type: boolean
      mypy-version:
        type: string
      mypy-args:
        type: string

jobs:
  pylint:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - name: Run pylint
        uses: GenapsysInc/internal-actions/reusable-actions/pylint@linter_action
        with:
          python-version: ${{ inputs.python-version }}
          requirements-txt: ${{ inputs.requirements-txt || null }}
          build-command: ${{ inputs.build-command || null }}
          pylint-version: ${{ inputs.pylint-version || null }}
          args: ${{ inputs.pylint-args || null }}
  mypy:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Run mypy
        uses: GenapsysInc/internal-actions/reusable-actions/mypy@linter_action
        with:
          python-version: ${{ inputs.python-version }}
          requirements-txt: ${{ inputs.requirements-txt || null }}
          build-command: ${{ inputs.build-command || null }}
          mypy-version: ${{ inputs.mypy-version || null }}
          args: ${{ inputs.mypy-args || null }}
