name: team-approval-action

on:
  [workflow_call, workflow_dispatch]:
    repo:
      description: "The repository to inspect"
      required: true
    pull:
      description: "The pull request number to inspect"
      required: true
    teams:
      description: "Teams required to be approvers"
      required: true

jobs:
  run_workflow:
    name: Run the team approval workflow
    runs-on: ubuntu-latest
    container:
      image: genapsysinc/team-approval-action:latest
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}
      args:
        - -s
        - ${{ secrets.GITHUB_TOKEN }}
        - -r
        - ${{ inputs.repo }}
        - -p
        - ${{ inputs.pull }}
        - -t
        - ${{ inputs.teams }}