name: team-approval-action

on:
  workflow_call:
    inputs:
      teams:
        description: "Teams required to be approvers"
        type: string
        required: true
    secrets:
      token:
        description: "Github PAT for authentication to REST API"
        required: true

jobs:
  run_workflow:
    name: Team Approval Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: genapsysinc/internal-actions
          path: internal-actions
          ref: submodule_check
          token: ${{ secrets.token }}
      - name: Set up Python 3.10
        uses: genapsysinc/internal-actions/reusable-actions/setup-py3@submodule_check
        with:
          requirements_txt: 'internal-actions/action_utils/requirements.txt'
      - name: Run get_team_approval_status.py with input args
        run: |
          python internal-actions/action_utils/get_team_approval_status.py \
            -s ${{ secrets.token }} \
            -r ${{ github.event.repository.name }} \
            -p ${{ github.event.pull_request.number }} \
            -t ${{ inputs.teams }}
