name: team-approval-check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  call-workflow:
    name: Run the team approval workflow
    runs-on: ubuntu-latest
    steps:
      - uses: genapsysinc/internal-actions/reusable-actions/team-approval@submodule_check_test
        with:
          teams: '"developer experience" inst-software'
          token: ${{ secrets.GH_REST_API_TOKEN }}
