name: team-approval-action

on:
  workflow_call:
    repo:
      description: "The repository to inspect"
      required: true
    pull:
      description: "The pull request number to inspect"
      required: true
    teams:
      description: "Teams required to be approvers"
      required: true
  workflow_dispatch:
    repo:
      description: "The repository to inspect"
      required: true
    pull:
      description: "The pull request number to inspect"
      required: true
    teams:
      description: "Teams required to be approvers"
      required: true

jobs:
  run_workflow:
    name: Run the team approval workflow
    container:
      image: gchr.io/genapsysinc/team-approval:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
      args:
        - -s
        - ${{ github.token }}
        - -r
        - ${{ inputs.repo }}
        - -p
        - ${{ inputs.pull }}
        - -t
        - ${{ inputs.teams }}