name: test-build-and-run
on:
  push:
    branches: [docker-build-upload-test]

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build image and load it
        uses: GenapsysInc/internal-actions/reusable-actions/docker-build-push@docker-build-upload
        with:
          context: .
          dockerfile: test-build/Dockerfile
          load: true
          tags: my-image:v1,my-image:latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: check images
        run: docker images
      - name: Run my image (v1)
        uses: GenapsysInc/internal-actions/reusable-actions/docker-run@docker-build-upload
        with:
          image: my-image:v1
          args: -c 'echo "hi you sure ran that image on v1"'
      - name: Run my image (latest)
        uses: GenapsysInc/internal-actions/reusable-actions/docker-run@docker-build-upload
        with:
          image: my-image:latest
          args: -c 'echo "hi you sure ran that image on latest"'
