name: test-team-approval-action

on:
  workflow_call:
    inputs:
      repo:
        description: "The repository to inspect"
        type: string
        required: true
      pull:
        description: "The pull request number to inspect"
        type: string
        required: true
      teams:
        description: "Teams required to be approvers"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repo:
        description: "The repository to inspect"
        type: string
        required: true
      pull:
        description: "The pull request number to inspect"
        type: string
        required: true
      teams:
        description: "Teams required to be approvers"
        type: string
        required: true

jobs:
  run_workflow:
    name: Run the team approval workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run get_team_approval_status.py with given arguments
        uses: dvmcconnell/docker-run-action@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: ghcr.io
          image: ghcr.io/genapsysinc/team-approval:latest
          args: -s ${{ secrets.TEAM_APPROVAL_TOKEN }} -r ${{ inputs.repo }} -p ${{ inputs.pull }} -t ${{ inputs.teams }}
