name: Run Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: genapsysinc/internal-actions/reusable-actions/setup-py3@submodule_check
      - name: Run tests
        run: python -m pytest -v
