name: Run Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.10' ]
    steps:
        - name: temp
          run: echo "hi"
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - name: Run unit tests
      #   uses: GenapsysInc/internal-actions/reusable-actions/pytest@code_cov
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     requirements-txt: action_utils/tests/requirements.txt
