name: Run Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'action-utils/tests/requirements.txt'
      - name: Install dependencies
        run: pip install -r action-utils/tests/requirements.txt
      - name: Run tests
        run: python -m pytest -v action_utils
