name: Run Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.10 and install dependencies
        uses: genapsysinc/internal-actions/reusable-actions/setup-python@submodule_check
        with:
          requirements-txt: 'action_utils/tests/requirements.txt'
      - name: Run tests
        run: python -m pytest -v
