name: Run Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.10' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'tests/requirements.txt'
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Run tests
        run: python -m pytest -v
